package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author jesus
 */
public class Administrativo extends javax.swing.JFrame {

    /**
     * Creates new form Administrativo
     */
    
    int x, y;
    public Administrativo() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        this.setIconImage(ico);
        this.setTitle("Administrativo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbdMover = new javax.swing.JLabel();
        lbdExit1 = new javax.swing.JLabel();
        lbdExit = new javax.swing.JLabel();
        lbdMin1 = new javax.swing.JLabel();
        lbdMin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbdReportes = new javax.swing.JLabel();
        lbdMulta = new javax.swing.JLabel();
        lbdPago = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 360));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel1.setText("C   O   M   U   I   N");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 400, 50));

        lbdMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbdMoverMouseDragged(evt);
            }
        });
        lbdMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdMoverMouseClicked(evt);
            }
        });
        jPanel3.add(lbdMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 30));

        lbdExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-10.png"))); // NOI18N
        lbdExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdExit1MouseClicked(evt);
            }
        });
        jPanel3.add(lbdExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 0, 10, 20));

        lbdExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/c3.png"))); // NOI18N
        lbdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbdExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbdExitMouseExited(evt);
            }
        });
        jPanel3.add(lbdExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 0, 20, 20));

        lbdMin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-10.png"))); // NOI18N
        lbdMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdMin1MouseClicked(evt);
            }
        });
        jPanel3.add(lbdMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 10, 20));

        lbdMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar 1.1.png"))); // NOI18N
        lbdMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbdMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbdMinMouseExited(evt);
            }
        });
        jPanel3.add(lbdMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 0, 20, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 650, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbdReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cabinete de archivos-64.png"))); // NOI18N
        jPanel1.add(lbdReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, 60));

        lbdMulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-documento-48.png"))); // NOI18N
        jPanel1.add(lbdMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, 60));

        lbdPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Billetes-48.png"))); // NOI18N
        jPanel1.add(lbdPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 60, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Generar Reporte");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Generar Multa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Generar Pago");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 650, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbdMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMoverMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lbdMoverMouseDragged

    private void lbdMoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMoverMouseClicked
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbdMoverMouseClicked

    private void lbdExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbdExit1MouseClicked

    private void lbdExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExitMouseEntered
        // TODO add your handling code here:
        lbdExit1.setVisible(true);
    }//GEN-LAST:event_lbdExitMouseEntered

    private void lbdExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExitMouseExited
        // TODO add your handling code here:
        lbdExit1.setVisible(false);
    }//GEN-LAST:event_lbdExitMouseExited

    private void lbdMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMin1MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbdMin1MouseClicked

    private void lbdMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinMouseEntered
        // TODO add your handling code here:
        lbdMin1.setVisible(true);
    }//GEN-LAST:event_lbdMinMouseEntered

    private void lbdMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinMouseExited
        // TODO add your handling code here:
        lbdMin1.setVisible(false);
    }//GEN-LAST:event_lbdMinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbdExit;
    private javax.swing.JLabel lbdExit1;
    private javax.swing.JLabel lbdMin;
    private javax.swing.JLabel lbdMin1;
    private javax.swing.JLabel lbdMover;
    private javax.swing.JLabel lbdMulta;
    private javax.swing.JLabel lbdPago;
    private javax.swing.JLabel lbdReportes;
    // End of variables declaration//GEN-END:variables
}
