
package ventanas;
import com.sun.awt.AWTUtilities;
import comuin.Conectar;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
/**
 *
 * @author jesus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    int x,y;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        this.setIconImage(ico);
        this.getContentPane().setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.lbdExit1.setVisible(false);
        this.lbdMinB.setVisible(false);
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbdExit1 = new javax.swing.JLabel();
        lbdExit = new javax.swing.JLabel();
        lbdMinB = new javax.swing.JLabel();
        lbdMinC = new javax.swing.JLabel();
        lbdIcono = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbdTextUsua = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lbdTexPass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lbdMover = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbdExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-10.png"))); // NOI18N
        lbdExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdExit1MouseClicked(evt);
            }
        });
        jPanel1.add(lbdExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 6, 10, 20));

        lbdExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/c3.png"))); // NOI18N
        lbdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbdExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbdExitMouseExited(evt);
            }
        });
        jPanel1.add(lbdExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 0, 20, 30));

        lbdMinB.setFont(new java.awt.Font("Segoe UI Light", 1, 40)); // NOI18N
        lbdMinB.setForeground(new java.awt.Color(255, 255, 255));
        lbdMinB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-10.png"))); // NOI18N
        lbdMinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdMinBMouseClicked(evt);
            }
        });
        jPanel1.add(lbdMinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 5, 10, 20));

        lbdMinC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar 1.1.png"))); // NOI18N
        lbdMinC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdMinCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbdMinCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbdMinCMouseExited(evt);
            }
        });
        jPanel1.add(lbdMinC, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 0, 20, 30));

        lbdIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-contraseña-48.png"))); // NOI18N
        jPanel1.add(lbdIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 50, 60));

        txtUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCaretPosition(0);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 155, 260, 20));

        lbdTextUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/text3.png"))); // NOI18N
        jPanel1.add(lbdTextUsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 290, 50));

        txtPass.setForeground(new java.awt.Color(102, 102, 102));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 255, 260, 20));

        lbdTexPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/text3.png"))); // NOI18N
        jPanel1.add(lbdTexPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 290, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-32.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-llave-30.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 40, 40));

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        lbdMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbdMoverMouseDragged(evt);
            }
        });
        lbdMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdMoverMouseClicked(evt);
            }
        });
        jPanel1.add(lbdMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 390, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C  O  M  U  I  N");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LumberJack´s");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-derechos-de-autor-10.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 490, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbdExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbdExitMouseClicked

    private void lbdMoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMoverMouseClicked
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbdMoverMouseClicked

    private void lbdMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMoverMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lbdMoverMouseDragged

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        // TODO add your handling code here:
        txtPass.setText("");
        txtPass.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPassMouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        Conectar obj = new Conectar();
        String usu;
        String pas;
        usu = txtUsuario.getText().replaceAll("[^a-zA-Z0-9]","");
        pas = txtPass.getText().replaceAll("[^a-zA-Z0-9]","");
        
        if(obj.verificar(usu, pas)){
            
        }else{
            JOptionPane.showMessageDialog(null,"Datos Incorrectos: ", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lbdExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbdExit1MouseClicked

    private void lbdMinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinBMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbdMinBMouseClicked

    private void lbdMinCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinCMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbdMinCMouseClicked

    private void lbdExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExitMouseEntered
        // TODO add your handling code here:
        lbdExit1.setVisible(true);
    }//GEN-LAST:event_lbdExitMouseEntered

    private void lbdExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdExitMouseExited
        // TODO add your handling code here:
        lbdExit1.setVisible(false);
    }//GEN-LAST:event_lbdExitMouseExited

    private void lbdMinCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinCMouseEntered
        // TODO add your handling code here:
        lbdMinB.setVisible(true);
    }//GEN-LAST:event_lbdMinCMouseEntered

    private void lbdMinCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdMinCMouseExited
        // TODO add your handling code here:
        lbdMinB.setVisible(false);
    }//GEN-LAST:event_lbdMinCMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbdExit;
    private javax.swing.JLabel lbdExit1;
    private javax.swing.JLabel lbdIcono;
    private javax.swing.JLabel lbdMinB;
    private javax.swing.JLabel lbdMinC;
    private javax.swing.JLabel lbdMover;
    private javax.swing.JLabel lbdTexPass;
    private javax.swing.JLabel lbdTextUsua;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
